version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "ably"
      MYSQL_DATABASE: "ably"
      MYSQL_USER: "ably"
      MYSQL_PASSWORD: "ably"
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 10
        sh run.sh
    tty: true
    environment:
      DB_HOST: "db"
      DB_NAME: "ably"
      DB_USER: "ably"
      DB_PASSWORD: "ably"
    volumes:
      - ./ably/:/app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
